###################################################################
# Seitentitel
###################################################################
header-title: "Voller Service und Support: Analyse, Webdesign und Entwicklung"
header-subtitle: Wir untersuchen Ihre Webseite, passen das Design an (oder machen ein neues) und entwickeln Ihre neue, moderne Webseite.

###################################################################
# Was wirklich wichtig ist Sektion
###################################################################
wichtig-title1: "Was wirklich wichtig ist:"
wichtig-text1-1: Beim Entwickeln einer Webseite ist es am besten, einen ganzheitlichen Ansatz zu verfolgen und die Bausteine auf Basis Ihrer spezifischen Anforderungen zusammenstellen. Der Webdesigner übernimmt die Führung während der Analyse- und Designphase, während gleichzeitig die Entwicklungsphase angestossen wird.
wichtig-img: <img src="/assets/images/colour-for-you-airbrush-meets-lifestyle-229x300.jpg" alt="">

###################################################################
# Was kostet eine Webseite Sektion
###################################################################
kosten-title1: <a href="/pages/was-wird-meine-neue-webseite-kosten">Was kostet eine professionelle Webseite von confidea?</a>
kosten-text1-1: Abhängig von Ihren Wünschen erstellen wir Ihnen ein individuelles Design für Ihre neue Webseite. Gerne machen wir Ihnen dafür ein Angebot.
kosten-text1-2: Wenn das Design vorliegt, sind wir in der Lage, Ihnen eine Webseite schon ab 750€ anzubieten.
kosten-text1-3: Sie können natürlich beliebig Module hinzufügen (Newslettersystem, Kontaktformular, Umfragen, Forum usw.).
kosten-text1-4: Sie bekommen also eine gut und sauber programmierte, zukunftssichere Webseite auf Basis eines vorgefertigten Designs bereits ab 750€.
kosten-text1-5: <a href="/pages/was-wird-meine-neue-webseite-kosten">Weitere Informationen</a>

###################################################################
# Callout Sektion
###################################################################
callout-1: Analyse
callout-1-text1-1: <i class="fa fa-eye fa-4x"></i>Jede großartige Webseite oder Online Marketing Aktion sollte mit einem Analyseprozess beginnen. Es ist wichtig zu verstehen, was Ihre Marke aussagen soll, wen Sie erreichen wollen und was Ihre Ziele für die Webseite sind. Ebenso wichtig ist es, Ihre Technologie oder Werkzeuge zu verstehen, die für Ihren Erfolg ausschlaggebend sind.
callout-1-text1-2: Unser für Sie ausgesuchter Webdesign Experte führt Sie durch den Analyseprozess und hilft Ihnen, eine professionelle Lösung für Ihre Bedürfnisse oder Erwartungen zu erarbeiten.

callout-2: Entwicklung
callout-2-text: <i class="fa fa-code-fork fa-4x"></i>Es ist unser Job, das von Ihnen freigegebene Design in eine funktionale Webseite zu verwandeln. <a href="/pages/webdesign-responsive-webseite">Wie hier näher beschrieben</a>, brauchen wir ca. eine Woche für die grundsätzliche Entwicklung. Der Designer ist während der Entwicklungsphase jederzeit involviert, falls wir weitere Grafiken oder Erläuterungen benötigen.

callout-3: Design
callout-3-text1-1: <i class="fa fa-paint-brush fa-4x"></i>Ihr Design muss Ihre Marke schnell und effizient kommunizieren und die Aufmerksamkeit Ihres Publikums erlangen. Es sollte den Webstandards entsprechen und toll aussehen, aber es muss auch reibungslos mit dem CMS und anderen Werkzeugen funktionieren.
callout-3-text1-2: Unser Webdesign Experte kann Ihre existierende Webseite nehmen und sie modernisieren. Oder er entwickelt mit Ihnen eine ganz neues Design. Auf jeden Fall wird das Design Ihnen helfen, Ihre Ziele zu erreichen.

callout-4: Schulung und Training
callout-4-text1-1: <i class="fa fa-graduation-cap fa-4x"></i>Sie brauchen Hilfe, um Ihr CMS (z. B. WordPress, Contao oder TYPO3) zu lernen? Wir haben eine Serie von Videos entwickelt, die wir Ihnen gern zur Verfügung stellen. Diese sind im jeweiligen Projektpreis enthalten.
callout-4-text1-2: Außerdem machen wir auch virtuelles "Training vor Ort". Dazu schalten wir uns mit den Computern Ihrer Mitarbeiter zusammen. So können wir gemeinsam an dem Projekt arbeiten und der Lerneffekt ist enorm.
