title: Dies ist der Webseitentitel
sitename: Dies ist der Webseitenname # Wird f체r SEO und Twitter genutzt
title-divider: " @ "
description: >
  Hier steht die Beschreibung, die lt. SEO nicht mehr als 156 Zeichen (inkl. Leerzeichen) haben soll
keywords: keyword1, keyword2, keyword3, keyword4, keyword5, keyword6, keyword7 # Nicht mehr als 7 Keywords

baseurl: "" # das Verzeichnis der Webseite, z. B. /blog/
url: "http://localhost:9999"

author: Vorname Nachname

owner:
  name: Vorname Nachname
  avatar: avatar.png
  bio:
  email: email@domain.tld
  disqus: # disqus shortname
  location: Ort, Land

twitter:
  username:
github:
  username:
skype:
  username:
instagram:
  username:
facebook:
  username:
dribble:
  username:
google_site_verification:
social:
  name: # Falls der Benutzer oder die Organisation von dem Seitennamen abweichen sollte
  links: # Eine Reihe von Links zu den Profilen der sozialen Medien

# Zus채tzliche Angaben f체r Humans.txt
webdesigner: Vorname Nachname
danke1:
  name: Vorname Nachname
  what: was-hat-gemacht
danke2:
  name: Vorname Nachname
  what: was-hat-gemacht
danke3:
  name: Vorname Nachname
  what: was-hat-gemacht
language: German
tools:
  standards: "HTML5, CSS3, Jekyll, JavaScript"
  software: "git, Atom, Gulp.js, npm"
host: Hostername
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Berlin

markdown: kramdown

incremental: true

source: ./app
destination: ./build

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

permalink: :title/

paginate: 5
paginate_path: "/page/:num/"

# Gulp k체mmert sich um Bilder und Assets
exclude: ['img', 'css', 'js', 'fonts', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico', 'img_README.md']

# Hier wird u. a. das Pages-Verzeichnis eingebunden
include: ['_pages', '.htaccess', 'robots.txt', 'humans.txt']

# `_config.build.yml` setzt `future` und `show_drafts` auf `false`
future: true
show_drafts: true
