#
# Diese Datei enthält notwendige Einstellungen für die Anpassungen der Webseite
#
#
# Titel der Webseite
title: Dies ist der Webseitentitel
#
# Trenner für Seitentitel und Webseite
title_divider: " @ "
#
# Kurze Beschreibung der Webseiteninhalts
description: >
  Hier steht die Beschreibung, die lt. SEO nicht mehr als 156 Zeichen (inkl. Leerzeichen) haben soll
#
# Nicht mehr als 7 gut ausgewählte Schlüsselwörter benutzen. Idealerweise sollten die seitenrelevanten Schlüsselworte im Front Matter der jeweiligen Seite aufgeführt werden
keywords: keyword1, keyword2, keyword3, keyword4, keyword5, keyword6, keyword7
#
# Das Verzeichnis der Webseite, z. B. /blog/
baseurl: ""
#
# Die URL der Webseite
url: "http://localhost:9999"
#
markdown: kramdown
#
# Jekyll macht die Builds nicht immer komplett neu, sondern inkrementell
incremental: true
#
# Verzeichnisse der Webseite und des Build
source: ./app
destination: ./build
#
# Wenn Collections genutzt werden sollen, müssen sie hier aufgeführt werden. Eine gute Anleitung gibt es hier: http://jxf.me/entries/custom-collections-jekyll/
collections:
  authors:
#
# Der Name des generellen Autors. Dieser Wert kann im Front Matter jeder Seite überschrieben werden
author: Vorname Nachname
#
# Personenbezogene Angaben
owner:
  name: Vorname Nachname
  # Falls es einen Avatar gibt, wird der im Verzeichnis `app/_assets/images` gespeichert
  avatar: avatar.png
  bio:
  location: Ort, Land
  mobile: +49 176 123 456 78
  phone: +49 5555 1234567
  # Einstellungen für das Kontaktformular. Es wird eine individuelle ID von Flipmail benötigt flipmail: http://flipmail.co/setup
  # Für das Verschlüsseln der Webseite: https://www.onsite.org/html/antispam_email.html
  email_encrypted:
  # Das Logo wird im Verzeichnis `app/_assets/images` gespeichert
  logo: logo.png
  # Bei Eintrag der Webseite in die Google Webmaster Tools wird eine HTML-Datei generiert, die sicherstellt, dass der Webseitenbetreiber identifiziert wurde
  google_site_verification:
#
# Dein Disqus-Kurname (nicht Dein Benutzername), um Kommentare der Beiträge zu aktivieren
# Deinen Kurznamen findest Du in den Einstellungen Deines Disqus-Kontos
disqus:
#
# Eingabe Deines Google Analytics Web Tracking Code (z.B. UA-2110908-2) um Tracking zu aktivieren
google_analytics:
#
# Hier kann "Ja" eingetragen werden, damit das Include funktioniert (siehe `_includes/analytics.html`)
piwik:
#
social_links:
  dribbble:
  email: email@domain.tld
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  # channel/<your_long_string> oder user/<user-name>
  youtube:
  # Irgendwas, das im Profilnamen nach plus.google.com/ vorkommt
  googleplus:
#
social:
  # Falls der Benutzer oder die Organisation von dem Seitennamen abweichen sollte
  name:
  # Eine Reihe von Links zu den Profilen der sozialen Medien
  links:
#
# Zusätzliche Angaben für die humans.txt
humans:
  webdesigner: Vorname Nachname
  danke1:
    name: Vorname Nachname
    what: was-hat-gemacht
  danke2:
    name: Vorname Nachname
    what: was-hat-gemacht
  danke3:
    name: Vorname Nachname
    what: was-hat-gemacht
  language: German
  tools:
    standards: "HTML5, CSS3, Jekyll, JavaScript"
    software: "git, Atom, Gulp.js, npm"
  host: Hostername
#
#
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Europe/Berlin
#
# Die folgenden Einstellungen müssen nicht geändert werden
#
permalink: :title/
#
paginate: 5
paginate_path: "/page/:num/"
#
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - i18n
#
# Gulp kümmert sich um Bilder und Assets
exclude:
  - img
  - css
  - js
  - fonts
  - '**.png'
  - '**.jpg'
  - '**.jpeg'
  - '**.gif'
  - '**.webp'
  - '**.svg'
  - '**.ico'
  - '_authors/authors-README.md'
#
# Hier wird u. a. das Pages-Verzeichnis eingebunden
include:
  - _pages
  - _authors
  - .htaccess
  - robots.txt
  - humans.txt
#
# `_config.build.yml` setzt `future` und `show_drafts` auf `false`
future: true
show_drafts: true
#
#
